### ISSUE TITLE
why image2col return 100 times the matrix?

### ISSUE THREAD

**Issue by sdiaa** [samehkhamis/pydeeplearn#1]
Many thanks! Hope you are progressing okay at works and all others. Both you&your family do take care!

In the Conv Forward layer located in /core/layers.py, you implemented the image2col in your code.  I noticed that the self._col after image2col is 100 times the original matrix.

For the example, the size of feature map is 1 (Depth) x 24 (Height) x 24 (Width) and that of kernel is 5 x 5. So the feature matrix after image2col is (1*5*5) x (24 * 24). But actual your cols is 25 x 57600.

And I outputted the cols and found that they are total same! Like self._cols[:,0] == self._cols[:,576]. I didn't know why.

**Comment by samehkhamis** [comment]
Thank you sdiaa.
I am actually no longer maintaining this code, but this behavior is correct.
im2ol extracts overlapping patches at the given stride. Please refer to a reference implementation. Caffe's is a good example.
